Document: icns
Title: Debian icns Manual
Author: <insert document author here>
Abstract: This manual describes what icns is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/icns/icns.sgml.gz

Format: postscript
Files: /usr/share/doc/icns/icns.ps.gz

Format: text
Files: /usr/share/doc/icns/icns.text.gz

Format: HTML
Index: /usr/share/doc/icns/html/index.html
Files: /usr/share/doc/icns/html/*.html

  
